### ISSUE TITLE
No work paper 1.20.4-429 please

### ISSUE THREAD

**Issue by Bujaejung** [Tschipcraft/dynamiclights#21]
### Describe the bug

There is a Reset and an Uninstall button.
I no see this command and this datapack 
My server don't work 

i need so many this datapack
Please ... thanks!

**Comment by Tschipcraft** [comment]
So both the commands `/trigger tschipcraft.menu` and `/function #tschipcraft:menu` do not show this menu when executed?

![Menu](https://raw.githubusercontent.com/Tschipcraft/dynamiclights/7a6b7997eec63182db586fbefcf06e0db1c169ef/wiki/menu.svg)

Did you move the .zip file into the `<world name>/datapacks` folder on the server? If yes, please send over the server log and try if the data pack gets displayed when running the command `/datapack list`

**Comment by Bujaejung** [comment]
oh very thank my god

![dy1](https://github.com/Tschipcraft/dynamiclights/assets/162647426/9b494b25-981c-43bf-b48f-100e37614b8f)
![dy2](https://github.com/Tschipcraft/dynamiclights/assets/162647426/2653b905-5b3a-4c3b-a0c0-8eb8c9702513)
![dy3](https://github.com/Tschipcraft/dynamiclights/assets/162647426/ec7acb52-7368-426c-a0f8-8fdcb6d1d0d1)
![dy4](https://github.com/Tschipcraft/dynamiclights/assets/162647426/427ed213-ba38-4b51-9809-fe00c0657ade)
![dy5](https://github.com/Tschipcraft/dynamiclights/assets/162647426/7bcca1d6-4fec-4b5f-9e92-d18c57d103e1)
![dy6](https://github.com/Tschipcraft/dynamiclights/assets/162647426/8fdd8f4f-5b79-4346-9d89-2b41cdf2897e)

**Comment by Tschipcraft** [comment]
Thanks. Could you additionally send or attach the latest log (located in the logs folder of the server)?

**Comment by Bujaejung** [comment]
yes!! this server log file thanks!!
[latest.log](https://github.com/Tschipcraft/dynamiclights/files/14538202/latest.log)

**Comment by Tschipcraft** [comment]
Thank you, this is an issue with the data pack CraftableEnchantedGoldenApple, since it specifies a minecraft:load tag with an invalid entry.
You should be able to fix Dynamic Lights by executing `/function dynamiclights:install_trigger`, however since this basically breaks the load entry point for other data packs as well, I'd recommend removing the entry `craftablenametag:force_restart` located in _CraftableEnchantedGoldenApple\data\minecraft\tags\functions\load.json_ instead.

Stack trace: `[08:21:21] [ServerMain/ERROR]: Couldn't load tag minecraft:load as it is missing following references: craftablenametag:force_restart (from file/CraftableEnchantedGoldenApple)`

**Comment by Bujaejung** [comment]
Thank you very much, developer. I will test it right away tomorrow morning!!

thanks i love this datapack.
have a good day!

**Comment by Bujaejung** [comment]
Thank you. I am using it well, but it seems that the data pack automatically terminates when the run time becomes long...!!

**Comment by Tschipcraft** [comment]
Interesting, I'm assuming you removed the faulty entry? After what time does it stop working?

**Comment by Tschipcraft** [comment]
Most likely related to #45. I will remove the question label and track this in the other thread
