### ISSUE TITLE
Problems when installing on client and server?

### ISSUE THREAD

**Issue by terrybougard** [Tschipcraft/dynamiclights#22]
### Describe the bug

After Typing /trigger tschipcraft.menu

Dynamic Light Setting won't appear.

If I use /function dynamiclights:settings

Dynamic Light Setting appears but the selections are empty.

![dynamic light settings empty](https://github.com/Tschipcraft/dynamiclights/assets/29400322/26a87485-c141-41f1-a6eb-af40936f2fc0)

**Comment by Tschipcraft** [comment]
Interesting... That's the first time _that_ happened.
Could you please send or attach your latest log file? (e.g. using [mclo.gs](https://mclo.gs/))

**Comment by terrybougard** [comment]
https://mclo.gs/f1MoJpz

**Comment by Tschipcraft** [comment]
Thanks, however this is a issue with mr_dungeons, since it specifies a minecraft:load tag with an invalid entry.
You should be able to fix Dynamic Lights by executing `/function dynamiclights:install_trigger`, however since this basically breaks the load entry point for other data packs as well, I'd recommend removing the entry `"techno.shared:load"` located in _mr_dungeons\data\minecraft\tags\functions\load.json_ instead and inform the author.

Stack trace: `[15:22:47] [main/ERROR]: Couldn't load tag minecraft:load as it is missing following references: techno.shared:load (from mr_dungeons`

**Comment by Tschipcraft** [comment]
Thanks! That's interesting, I'll have a look at that

**Comment by Tschipcraft** [comment]
I haven't found any problems when installing Dynamic Lights on both client and server, so I will close this issue for now. If anyone still encounters this, feel free to reopen this thread.
