### ISSUE TITLE
Feature Request - make lava cauldrons glow

### ISSUE THREAD

**Issue by onebeastchris** [Tschipcraft/dynamiclights#4]
Hey there, still sick pack. 

I noticed lava cauldrons don't glow, see here - [300a628f-39bb-4ae6-85b0-8d5d2e1e1f50.png](https://user-images.githubusercontent.com/105284508/228238768-7ce343d4-c042-469d-a603-f2cecfb5c89a.png)

Would it be possible for them to?
Thanks!

**Comment by Tschipcraft** [comment]
Hello again,

I'm surprised you got this data pack working on Minecraft Bedrock edition, but judging by your GitHub activity, you found your ways.

This data pack focuses on adding dynamic lightning to items. In the screenshot, however, a placed block is not emitting any light. This may be a bug in the base game, whether it be the Bedrock client or the underlying Java server, or in the software making cross play possible.
Since in vanilla Minecraft placed lava cauldrons do glow, this bug should be resolved by the developers of the software mentioned above and not by my data pack which doesn't focus on cross play compatibility.
Please try to report this bug to for example the Geyser team first.

Cheers, Tschipcraft

**Comment by onebeastchris** [comment]
shit, forgot that it's a block and not an item. Sorry!

As for the pack - since you're using lightblocks, which also exist on bedrock, this pack works flawlessly with Geyser!
I'll see if this Geyser bug can be fixed; sorry for the false alarm. Appreciate the response!
