### ISSUE TITLE
Annoyances when installed alongside Litematica or Tweakeroo

### ISSUE THREAD

**Issue by wilebaldo** [Tschipcraft/dynamiclights#47]
### Describe the bug

If I have activated the the option "enchanted items" in this mod, and later I have activated a schematic is show in the head a block pink, and is a problem with the view of the schematic. and also when I have the tweakeroo the light level on the block activated the level light change in the block is not direct i changed like if is.

In the first moment I was thinking the problem was those mods and I reported with them, but they let me know the problem was another mod, and I test all of them until I notice this was the problem.

I hope this images can help to show the problem.

![Screenshot 2024-08-05 at 23 04 46](https://github.com/user-attachments/assets/c99868e5-da7f-4457-9de9-fd149f67b6ed)
![Screenshot 2024-08-05 at 23 04 52](https://github.com/user-attachments/assets/0728fc77-0d58-40b3-8325-182ed475cfa6)
![Screenshot 2024-08-05 at 23 05 15](https://github.com/user-attachments/assets/c0f1dbcd-eaf3-4b43-b379-2000dda4be55)
![Screenshot 2024-08-05 at 23 05 21](https://github.com/user-attachments/assets/29358ea8-c433-49ef-bfdd-7b138635dd39)
![Screenshot 2024-08-05 at 23 05 29](https://github.com/user-attachments/assets/50bda903-d29b-49e8-b646-656136eb3102)
![Screenshot 2024-08-05 at 23 11 54](https://github.com/user-attachments/assets/c04c3703-ef65-4a6d-9480-4e92790557a8)
![Screenshot 2024-08-05 at 23 12 10](https://github.com/user-attachments/assets/ec8c2ef9-38e8-40b9-99c9-93fe46560161)
![Screenshot 2024-08-05 at 23 12 34](https://github.com/user-attachments/assets/e5af2329-2cb8-4619-aa3f-e2136f119a21)

### Additional context

Before in used the LambDynamicLights and not this mod with Minecraft 1.20.4 and before and I don't have this problems, this started with this mod and with Minecraft 1.21

**Comment by Tschipcraft** [comment]
I'm not really sure what the issue is here. In contrast to LambDynamicLights, this project actually registers the light on the server. So what you are seeing here are the effects of this.
In the first five screenshots, tweakeroo is showing you the changed light levels coming from the enchanted armor of your player. If it were night, they would behave like the normal light levels and e.g. not let mobs spawn around you.
In the last three screenshots, litematica (I assume at least?) is showing you that there is a light emitting block where your player is that is not in the schematic. If this is annoying, there could be a setting in litematica to exclude certain blocks from being highlighted. I say could since I haven't played in a while. If this is the case, the block ID to exclude is called `minecraft:light`.

Both of these make perfect sense in what they want to achieve/show to you, so I'd say this works as intended.

**Comment by wilebaldo** [comment]
More late I will tested again and try to make those changes.

**Comment by wilebaldo** [comment]
OK, I did some small tests first with one of the mods (tweakeroo), and one of the functions I use the most, the level light of the block.

In this first clip I show the old mod I used on minecraft 1.20.4 and before to have a Light Dynamics in the game, and I show you how is the ilumination on the spawnable blocks with the mod tweakeroo. This was my normal use for many years.

https://youtu.be/WBCUv0Is-K0?si=qsMZccuit1Wsa3Ze

In this second clip I show you this new mod that is the best and only available for minecraft 1.21, and like you can see is different show how the mods works together, DynamicLights and Tweakeroo.

https://youtu.be/XkWpIyTUWIQ

This third clip is comparing both mods in a cave.

https://youtu.be/ACgNJCDG4bQ

I will make some test with the other mod, but for now this is the issue I have. Well for me is and "issue", but maybe this new mods is the way is working and is make to work like that, and if that is the case well, I have nothing more to do.

Thanks.

**Comment by wilebaldo** [comment]
I make same test but now with the litematica, this is the video to show you how is the issue. more or less I fixed changing the option item enchanted like a light source, maybe not necesary to change nothing on the mod for this, maybe is the way how is works, but anyway I will live here the video so you can see it.

https://youtu.be/0MBqdPDdOlY

**Comment by Tschipcraft** [comment]
Thanks for the additional videos. I can see how it's a bit annoying to work with, but as stated in my previous response, all the mods are doing their job correctly. Unlike to LambDynamicLights, (since this is server-side and not client-side) this project does not "fake" the light and actually places a block that emits the light, causing both tweakeroo and litematica to inform you.
I will add a toggle to disable per player dynamic lights in a future update (see #37), which could be used in this situation to make it less annoying.

<details>
<summary>Traducción al español (Spanish translation)</summary>

Gracias por los vídeos adicionales. Puedo ver como es un poco molesto trabajar con esto, pero como dije en mi respuesta anterior, todos los mods están haciendo su trabajo correctamente. A diferencia de LambDynamicLights, (ya que esto es del lado del servidor y no del lado del cliente) este proyecto no "finge" la luz y en realidad coloca un bloque que emite la luz, haciendo que tanto tweakeroo como litematica le informen.
Añadiré un toggle para desactivar las luces dinámicas por jugador en una futura actualización (ver #37), que podría usarse en esta situación para hacerlo menos molesto.
</details>
