### ISSUE TITLE
Incompatible with MCPitanLib in 1.21

### ISSUE THREAD

**Issue by GuyFromTheInternet** [Tschipcraft/dynamiclights#49]
### Steps to reproduce

1. Install MCPitanLib

### Expected behavior

It should work

**Comment by Tschipcraft** [comment]
I ran a quick test in Minecraft 1.20.1 with Dynamic Lights v1.8.3 and MCPitanLib 2.3.3, and it seems to be working just fine.
Could you add any additional information to this issue? Please include mod version numbers and your most recent minecraft log.

**Comment by GuyFromTheInternet** [comment]
1.21 Forgot to mention

**Comment by Tschipcraft** [comment]
Thanks. I'm not sure what MCPitanLib is doing. Looks like it's using the old version of a tag file located in the old folder format (pre 1.21) and tries to load a dependency of it in the new folder format, which makes absolutely no sense. By the looks of things, the source code of MCPitanLib for 1.21 is not even available on their GitHub, so there's nothing I can do. Since this breaks the vanilla behavior, I'd report this on their repo to get it fixed.

The only warning connected to this: `Not all defined tags for registry ResourceKey[minecraft:root / minecraft:entity_type] are present in data pack: dynamiclights:reparse_interactible` (reparse_interactible does not exist in the new folder format, but is not normally called. Because of this error, the entity tags fail to load, which ultimately disables the whole data pack since there are no entities to select)

**Comment by GuyFromTheInternet** [comment]
I think the MCPitanLib was moved to https://github.com/Pitan76/MCPitanLib/tree/1.21

**Comment by Tschipcraft** [comment]
Thanks for letting me know, the Modrinth page is still linking to the old repo

**Comment by Tschipcraft** [comment]
This has been fixed as of MCPitanLib-2.3.3-fix.1 🎉
