### ISSUE TITLE
Can overwrite existing player-placed light blocks

### ISSUE THREAD

**Issue by sydist** [Tschipcraft/dynamiclights#7]
### Describe the bug

Title says it all really, if you're playing a Minecraft map or something that has player-placed light blocks by the map builders, this will overwrite those and can remove them.

### Expected behavior

Light blocks placed by players should not be touched.

**Comment by Tschipcraft** [comment]
Thanks for the bug report!

**Comment by sydist** [comment]
May I ask how this was fixed?

**Comment by Tschipcraft** [comment]
Sure. I just added a condition in the update functions in internal/place_light/ to abort the whole process if a light block exists without a marker entity of Dynamic Lights at the current position.
This may not work well if the placed light block has a low light level, since dynamic lights no longer work at that position, but otherwise I would have had to rewrite the no_space_resolve function or add additional data to the marker entities to reset the player-placed light block to its original light level after the dynamic light has moved, which would have added unnecessary overhead for normal use.

**Comment by sydist** [comment]
Oh I see, that's pretty cool!
Thanks for clarifying
