### ISSUE TITLE
make the light smoother

### ISSUE THREAD

**Issue by ExWhyZedd0** [Tschipcraft/dynamiclights#9]
### Is your feature request related to a problem? Please describe.

Hey pal ! First off, nice pack. Love it so much !

### Describe the feature you'd like

i noticed that the light is not smooth
so can you  add something to make the light smoother ?

**Comment by Tschipcraft** [comment]
Thanks <3
Since I'm using the light block for this data pack, I'm sadly limited to the block grid for the dynamic lights.

The only way I could achieve more smoothness is using something like Bradleyq's Light Painter project that uses a resource pack with shaders to achieve colored dynamic lightning. Recreating the vanilla look of light sources with this approach would however require a lot of tweaking and players would have to install the resource pack ofc.

<a href="https://github.com/bradleyq/light_painter">
  <picture>
    <source 
      srcset="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=light_painter&theme=github_dark&show_owner=true&border_color=30363d"
      media="(prefers-color-scheme: dark)"
      height=140px
    />
    <source
      srcset="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=light_painter&theme=default&show_owner=true"
      media="(prefers-color-scheme: light), (prefers-color-scheme: no-preference)"
      height=140px
    />
    <img height=140px src="https://github-readme-stats.vercel.app/api/pin/?username=bradleyq&repo=light_painter&theme=transparent&show_owner=true" alt="Bradleyq's Light Painter"/>
  </picture> 
</p>

**Comment by ExWhyZedd0** [comment]
tysm for your reply, i will look through it

**Comment by Tschipcraft** [comment]
I have to add to my response, that the project I mentioned does not natively support dynamic lights and focuses more on bringing player-placed colored lights into the game, so you would have to write some code around that to achieve something similar like this data pack.

**Comment by ExWhyZedd0** [comment]
so after i checked it, i forgot to tell you that i playing on 1.20.1. is it okay if i use this or theres other data pack ?

**Comment by Tschipcraft** [comment]
This data pack right here does not support Bradleyq's light painter project at this time (but may in the future, who knows).
I don't think there's another data pack, or at least I haven't seen one, that achieves more smoothness or integrates into the mentioned light painter. So yes, you are welcome to use this data pack, but you'll sadly have to live with the choppy lights for now (or use a mod)

**Comment by ExWhyZedd0** [comment]
oh okay, tysm for the information !!
